Lesson3
KrutkoAndrii/ITEA_Python_basics pull request #2
Opened 2019-06-12 19:39 UTC by KrutkoAndrii

урок со всеми изменениями, согласно указаний. + задания по уроку 3

2019-06-13 14:25 UTC, itea-artem requested changes

2019-06-13 14:25 UTC, itea-artem commented on .idea/ITEA_Python_basics.iml
> +<?xml version="1.0" encoding="UTF-8"?>
gitignore

2019-06-13 14:25 UTC, itea-artem commented on lesson2/Homework_2_2.py
>      if digit_base == 0:
PEP8 file name

2019-06-13 14:25 UTC, itea-artem commented on lesson2/lesson2_def.py
> +    list_digit = list.split(",")
```suggestion
    digit_list= list.split(",")
```

2019-06-13 14:25 UTC, itea-artem commented on lesson2/lesson2_def.py
> +def get_summ_digit(digit):
```suggestion
def get_sum_digit(digit):
```

2019-06-13 14:25 UTC, itea-artem commented on lesson2/lesson2_def.py
> +    sort_sum = []
Variable should start with noun, not with verb.
```suggestion
    sorted_sum = []
```

2019-06-13 14:25 UTC, itea-artem commented on lesson2/lesson2_def.py
> +    while fl is False:
Very inefficient code. Find bubble sort on python online. Will give more explanations on the next lesson.

2019-06-13 14:25 UTC, itea-artem commented on lesson2/lesson2_rekursiya.py
> +def get_sum_digit_of_numeric(num, lenght_string):
First of all, length of string '123' is 3, not 2.
Don't pass the length of string to function, because you can get length with len(var_name)
Functions should be outside main.

2019-06-13 14:25 UTC, itea-artem commented on lesson3/lesson3_2.py
> +    print("Sum of matrix is: "+str(get_sum_matrix(incoming_matrix, length, high)))
```suggestion
    print("Sum of matrix is: ", get_sum_matrix(incoming_matrix, length, high))
```

2019-06-13 14:25 UTC, itea-artem commented on lesson3/lesson3_6_7_8_9.py
> +    def show_dict():
Avoid nested functions if possible

2019-06-14 10:16 UTC, KrutkoAndrii commented on lesson3/lesson3_2.py
> +    print("Sum of matrix is: "+str(get_sum_matrix(incoming_matrix, length, high)))
Traceback (most recent call last):
  File "C:/Users/a.krutko.EXIM/Documents/ITEA_Python_basics/lesson3/lesson3_2.py", line 36, in <module>
    print("Sum of matrix is: " + get_sum_matrix(incoming_matrix, length, high))
TypeError: can only concatenate str (not "int") to str

2019-06-22 11:40 UTC, pep8speaks commented
Hello @KrutkoAndrii! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

















* In the file [`lesson2/lesson2_def.py`](https://github.com/KrutkoAndrii/ITEA_Python_basics/blob/f3eb387f0f7d446e7689a0dda16ad48a2a7faecd/lesson2/lesson2_def.py):

> [Line 48:1](https://github.com/KrutkoAndrii/ITEA_Python_basics/blob/f3eb387f0f7d446e7689a0dda16ad48a2a7faecd/lesson2/lesson2_def.py#L48): [E115](https://duckduckgo.com/?q=pep8%20E115) expected an indented block (comment)

* In the file [`lesson2/lesson2_rekursiya.py`](https://github.com/KrutkoAndrii/ITEA_Python_basics/blob/f3eb387f0f7d446e7689a0dda16ad48a2a7faecd/lesson2/lesson2_rekursiya.py):

> [Line 4:80](https://github.com/KrutkoAndrii/ITEA_Python_basics/blob/f3eb387f0f7d446e7689a0dda16ad48a2a7faecd/lesson2/lesson2_rekursiya.py#L4): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 24:1](https://github.com/KrutkoAndrii/ITEA_Python_basics/blob/f3eb387f0f7d446e7689a0dda16ad48a2a7faecd/lesson2/lesson2_rekursiya.py#L24): [E115](https://duckduckgo.com/?q=pep8%20E115) expected an indented block (comment)



* In the file [`lesson3/lesson3_2.py`](https://github.com/KrutkoAndrii/ITEA_Python_basics/blob/f3eb387f0f7d446e7689a0dda16ad48a2a7faecd/lesson3/lesson3_2.py):

> [Line 13:80](https://github.com/KrutkoAndrii/ITEA_Python_basics/blob/f3eb387f0f7d446e7689a0dda16ad48a2a7faecd/lesson3/lesson3_2.py#L13): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (95 > 79 characters)
> [Line 35:80](https://github.com/KrutkoAndrii/ITEA_Python_basics/blob/f3eb387f0f7d446e7689a0dda16ad48a2a7faecd/lesson3/lesson3_2.py#L35): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (98 > 79 characters)

* In the file [`lesson3/lesson3_3.py`](https://github.com/KrutkoAndrii/ITEA_Python_basics/blob/f3eb387f0f7d446e7689a0dda16ad48a2a7faecd/lesson3/lesson3_3.py):

> [Line 13:80](https://github.com/KrutkoAndrii/ITEA_Python_basics/blob/f3eb387f0f7d446e7689a0dda16ad48a2a7faecd/lesson3/lesson3_3.py#L13): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (111 > 79 characters)
> [Line 29:80](https://github.com/KrutkoAndrii/ITEA_Python_basics/blob/f3eb387f0f7d446e7689a0dda16ad48a2a7faecd/lesson3/lesson3_3.py#L29): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)

* In the file [`lesson3/lesson3_4.py`](https://github.com/KrutkoAndrii/ITEA_Python_basics/blob/f3eb387f0f7d446e7689a0dda16ad48a2a7faecd/lesson3/lesson3_4.py):

> [Line 21:80](https://github.com/KrutkoAndrii/ITEA_Python_basics/blob/f3eb387f0f7d446e7689a0dda16ad48a2a7faecd/lesson3/lesson3_4.py#L21): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (95 > 79 characters)
> [Line 30:80](https://github.com/KrutkoAndrii/ITEA_Python_basics/blob/f3eb387f0f7d446e7689a0dda16ad48a2a7faecd/lesson3/lesson3_4.py#L30): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (92 > 79 characters)
> [Line 38:80](https://github.com/KrutkoAndrii/ITEA_Python_basics/blob/f3eb387f0f7d446e7689a0dda16ad48a2a7faecd/lesson3/lesson3_4.py#L38): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (101 > 79 characters)



* In the file [`lesson3/lesson3_6_7_8_9.py`](https://github.com/KrutkoAndrii/ITEA_Python_basics/blob/f3eb387f0f7d446e7689a0dda16ad48a2a7faecd/lesson3/lesson3_6_7_8_9.py):

> [Line 31:80](https://github.com/KrutkoAndrii/ITEA_Python_basics/blob/f3eb387f0f7d446e7689a0dda16ad48a2a7faecd/lesson3/lesson3_6_7_8_9.py#L31): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 32:80](https://github.com/KrutkoAndrii/ITEA_Python_basics/blob/f3eb387f0f7d446e7689a0dda16ad48a2a7faecd/lesson3/lesson3_6_7_8_9.py#L32): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 33:80](https://github.com/KrutkoAndrii/ITEA_Python_basics/blob/f3eb387f0f7d446e7689a0dda16ad48a2a7faecd/lesson3/lesson3_6_7_8_9.py#L33): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 34:80](https://github.com/KrutkoAndrii/ITEA_Python_basics/blob/f3eb387f0f7d446e7689a0dda16ad48a2a7faecd/lesson3/lesson3_6_7_8_9.py#L34): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 35:80](https://github.com/KrutkoAndrii/ITEA_Python_basics/blob/f3eb387f0f7d446e7689a0dda16ad48a2a7faecd/lesson3/lesson3_6_7_8_9.py#L35): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)
> [Line 36:80](https://github.com/KrutkoAndrii/ITEA_Python_basics/blob/f3eb387f0f7d446e7689a0dda16ad48a2a7faecd/lesson3/lesson3_6_7_8_9.py#L36): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)
> [Line 47:80](https://github.com/KrutkoAndrii/ITEA_Python_basics/blob/f3eb387f0f7d446e7689a0dda16ad48a2a7faecd/lesson3/lesson3_6_7_8_9.py#L47): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (102 > 79 characters)
> [Line 85:80](https://github.com/KrutkoAndrii/ITEA_Python_basics/blob/f3eb387f0f7d446e7689a0dda16ad48a2a7faecd/lesson3/lesson3_6_7_8_9.py#L85): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 104:80](https://github.com/KrutkoAndrii/ITEA_Python_basics/blob/f3eb387f0f7d446e7689a0dda16ad48a2a7faecd/lesson3/lesson3_6_7_8_9.py#L104): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (102 > 79 characters)

2019-06-23 18:19 UTC, closed without merging